const api=location.origin;
const theme=document.createElement('link');theme.rel='stylesheet';theme.href='/app/moon.css';document.head.append(theme);
document.querySelector('nav').insertAdjacentHTML('afterend','<section class="moon-core"><div class="orb">☾</div><h2>MOON</h2><p>Your computer, understood.</p><div class="alert">System awareness online</div></section>');
const orb=document.querySelector('.moon-core .orb');orb.textContent='';orb.style.backgroundImage="url('/app/assets/moon-lunar.png')";orb.style.backgroundSize='cover';
function ring(selector,value,label,color){const el=document.querySelector(selector),n=Math.min(100,Math.round(value));el.style.background=`radial-gradient(circle,#111a35 57%,transparent 58%),conic-gradient(${color} ${n*3.6}deg,rgba(157,187,255,.12) 0deg)`;el.querySelector('strong').textContent=`${n}%`;el.querySelector('small').textContent=label}
async function load(){try{const s=await(await fetch(`${api}/status`)).json();ring('.cpu',s.cpu.usage_percent,'live','#9dbbff');ring('.memory',s.memory.usage_percent,`${s.memory.available_gb} GB free`,'#ffc979');ring('.storage',s.storage.usage_percent,`${s.storage.free_gb} GB free`,'#ffc979');const f=[];if(s.storage.usage_percent>=90)f.push(`Storage is nearly full — ${s.storage.free_gb} GB free.`);if(s.memory.usage_percent>=80)f.push(`Memory use is high — ${s.memory.available_gb} GB available.`);document.querySelector('#findings').innerHTML=(f.length?f:['No immediate system warning found.']).map(x=>`<div class="finding"><b>⚠</b> ${x}</div>`).join('');const t=await(await fetch(`${api}/tasks`)).json();document.querySelector('#tasks').innerHTML=t.tasks.length?t.tasks.slice(0,4).map(x=>`<div class="event">${x.objective} · ${x.state}</div>`).join(''):'No investigations recorded yet.'}catch(e){document.querySelector('#activity').textContent='Moon could not reach the local runtime. Start run_api.py and refresh.'}}
async function runMonitor(){const d=await(await fetch(`${api}/monitor/check`)).json();document.querySelector('#activity').textContent=d.message}
async function askMoon(){const i=document.querySelector('#request'),r=document.querySelector('#reply');if(!i.value.trim())return;r.textContent='Moon is investigating…';try{const t=await(await fetch(`${api}/tasks/slow-computer`,{method:'POST'})).json();r.textContent=`Investigation complete: ${t.result.recommended_next_step}`;i.value='';load()}catch(e){r.textContent='Moon could not complete that request.'}}
load();
const links={docs:'/app/docs.html','release-notes':'/app/release-notes.html',github:'/app/github.html'};
Object.entries(links).forEach(([id,href])=>{const footer=document.getElementById(id);if(footer)footer.href=href;document.querySelectorAll(`a[href="#${id}"]`).forEach(link=>link.href=href)});
const subtitle=document.querySelector('.nav-brand small');if(subtitle)subtitle.style.fontSize='8px';
